[project]
name = "qonto-mcp-server"
version = "0.1.0"
description = "MCP Server for the Qonto API."
authors = [
    { name = "j-about", email = "142051449+j-about@users.noreply.github.com" }
]
requires-python = ">=3.13.3"
dependencies = [
    "httpx==0.28.1",
    "mcp[cli]==1.8.0",
]
